### PR TITLE
dropping support for python 2.7

### PR DESCRIPTION
**Pull request by flip111**
due to https://github.com/hartwork/svneverever/issues/6

### CODE REVIEW

**Comment by flip111** [comment]
I don't see these things in the readme.

**Comment by hartwork** [comment]
They are not in the readme but in other files. My point is that we go for `python3` here than the other places are not in sync any more so the pull request introduces a new problem so to say. Does that make sense?

**Comment by flip111** [comment]
Yes it makes sense. Though wasn't this "out of sync" state not already initiated in #6 ?

**Comment by hartwork** [comment]
The out-of-sync produced by #6 is the "2.7/" leftover at the core. It's fixable without producing new out-of-syncs, either by sticking to `python` or by using `python3` consistently.

**Comment by flip111** [comment]
Ok i'll have a look at changing to python3 in other places too

**Comment by hartwork** [comment]
Thank you!

**Pull request merged**
